#!/usr/bin/env bash
# Build the project and check that no non-standard axioms are used.
set -euo pipefail
cd "$(dirname "$0")"

echo "== lake build =="
lake build

echo
echo "== axiom check =="
cat > .axiomcheck.lean <<'EOF'
import RobinCaps
#print axioms RobinCaps.Interval.existsUnique_phaseRoot
#print axioms RobinCaps.Interval.phaseFun_strictMonoOn
#print axioms RobinCaps.Interval.phaseFun_tendsto_zero
#print axioms RobinCaps.Interval.phaseRoot_lt_rightEnd
#print axioms RobinCaps.Interval.leftEnd_lt_phaseRoot
#print axioms RobinCaps.Interval.phaseRoot_scaling
#print axioms RobinCaps.Interval.mu_scaling
#print axioms RobinCaps.Interval.rootSym_strictMonoOn
#print axioms RobinCaps.Interval.gap_strictMonoOn
#print axioms RobinCaps.Interval.gap_tendsto
#print axioms RobinCaps.Interval.mu_perturbation_bound
#print axioms RobinCaps.Interval.mu_O_R
#print axioms RobinCaps.Cap.sharp_cap_inequality_F
#print axioms RobinCaps.Cap.beta_ge_beta0
#print axioms RobinCaps.Cap.equality_iff_F
#print axioms RobinCaps.Cap.hemisphere_equality
#print axioms RobinCaps.Cap.volume_body_eq_of_cap
#print axioms RobinCaps.Cap.Concave.profileAC_of_cap
#print axioms RobinCaps.Sobolev.robinMinmaxQ_one_eq_mu
#print axioms RobinCaps.Sobolev.robinMinmaxQ_two_eq_mu
#print axioms RobinCaps.Sobolev.gap_eq_robinMinmaxQ
#print axioms RobinCaps.Sobolev.robinMinmaxQ_le_mu
#print axioms RobinCaps.Domain.diam_capsule
#print axioms RobinCaps.Domain.beta0_lt
#print axioms RobinCaps.Domain.counterexample_of_asymptotics_diam
#print axioms RobinCaps.Domain.beta0_ratio_one
#print axioms RobinCaps.Cap.EqualityAC.equality_iff_AC
#print axioms RobinCaps.Sobolev.PiconeGeneral.robinMinmaxQ_eq_mu
#print axioms RobinCaps.ThinDomain.map_heightSplit
#print axioms RobinCaps.ThinDomain.integral_sphere_slicing
#print axioms RobinCaps.ThinDomain.capLateralIntegral_hemisphere_eq
#print axioms RobinCaps.ThinDomain.traceDataOne
#print axioms RobinCaps.ThinDomain.hasTraceData_one
#print axioms RobinCaps.ThinDomain.traceForm_eq
#print axioms RobinCaps.ThinDomain.ball_trace_ineq_c1
#print axioms RobinCaps.ThinDomain.cap_upper_J
#print axioms RobinCaps.ThinDomain.renormEnergy_trialH1P
#print axioms RobinCaps.ThinDomain.trialEnergyTarget
#print axioms RobinCaps.ThinDomain.trialMassTarget
#print axioms RobinCaps.ThinDomain.bdSliceable_bdTr
#print axioms RobinCaps.ThinDomain.hasWeakGradP_trialAC
#print axioms RobinCaps.ThinDomain.bulkProjThin_surjective_trialAC
#print axioms RobinCaps.ThinDomain.massP_trialAC
#print axioms RobinCaps.ThinDomain.dirichletP_trialAC
#print axioms RobinCaps.ThinDomain.massQ_le_massPQ_liftQ
#print axioms RobinCaps.ThinDomain.transverseExpansionData_one
#print axioms RobinCaps.ThinDomain.trial_mass_one
#print axioms RobinCaps.ThinDomain.trial_energy_one
#print axioms RobinCaps.ThinDomain.trial_energy_field_one
#print axioms RobinCaps.ThinDomain.trial_mass_field_one
#print axioms RobinCaps.ThinDomain.renormEnergy_trialAC_ta
#print axioms RobinCaps.Sobolev.Weak.radialSlice_ae
#print axioms RobinCaps.Sobolev.Weak.radialSlice_h1
#print axioms RobinCaps.Sobolev.Weak.traceSphere_sq_integral_le
#print axioms RobinCaps.Sobolev.Weak.traceSphere_eq_of_continuous
#print axioms RobinCaps.ThinDomain.ifaceL_spec
#print axioms RobinCaps.ThinDomain.integral_ifaceL_sq_le
#print axioms RobinCaps.ThinDomain.entranceVal_capLeft
#print axioms RobinCaps.ThinDomain.axial_poincare_capLeft
#print axioms RobinCaps.ThinDomain.integrableOn_entranceVal_sq_capLeft
#print axioms RobinCaps.ThinDomain.globalComparisonData_one_a1
#print axioms RobinCaps.ThinDomain.mainTheorem_one_a1
#print axioms RobinCaps.ThinDomain.counterexample_one_a1
#print axioms RobinCaps.ThinDomain.lower_rep_a1
#print axioms RobinCaps.ThinDomain.upper_rep_a1
#print axioms RobinCaps.Cap.cap_lower_weak_p
#print axioms RobinCaps.Cap.cap_mass_bound_weak_p
#print axioms RobinCaps.Cap.weighted_poincare_lw
#print axioms RobinCaps.Cap.cap_lower_weak_transverse
#print axioms RobinCaps.ThinDomain.trialEnergyInput_one_bt
#print axioms RobinCaps.ThinDomain.traceIneqOne_hemisphere
#print axioms RobinCaps.ThinDomain.bulk_trace_bound_st
#print axioms RobinCaps.ThinDomain.arc_trace_bound_st
#print axioms RobinCaps.ThinDomain.profileEndpoint_left_pe
#print axioms RobinCaps.ThinDomain.bulkProjThin_endpoint_left_pe
#print axioms RobinCaps.ThinDomain.profile_eq_integral_iface_pe
#print axioms RobinCaps.ThinDomain.mainTheorem_gen_ag
#print axioms RobinCaps.ThinDomain.counterexample_gen_ag
#print axioms RobinCaps.ThinDomain.trialEnergyInput_gen_ag
#print axioms RobinCaps.ThinDomain.mainTheorem_one_ag
#print axioms RobinCaps.ThinDomain.interfaceTraceInput_one_bi
#print axioms RobinCaps.ThinDomain.vert_eq_rad_vr
#print axioms RobinCaps.ThinDomain.ae_eq_of_pair_bound_vr
#print axioms RobinCaps.ThinDomain.arcTraceSt_of_fields_vr
#print axioms RobinCaps.ThinDomain.reflectEven_hasWeakGrad
#print axioms RobinCaps.ThinDomain.mass_reflectEven
#print axioms RobinCaps.ThinDomain.gammaTrace_sq_integral_le
#print axioms RobinCaps.ThinDomain.capLateralIntegral_gammaTrace_sq_le
#print axioms RobinCaps.ThinDomain.gammaTrace_eq_of_continuous
#print axioms RobinCaps.ThinDomain.capLowerInput_one_bc
#print axioms RobinCaps.ThinDomain.capEnergyW_capLeft_bc
#print axioms RobinCaps.ThinDomain.pCoefW_capLeft_one_bc
#print axioms RobinCaps.ThinDomain.traceIneqOne_hemisphere_br
#print axioms RobinCaps.ThinDomain.radialACL_br
#print axioms RobinCaps.ThinDomain.vertRadIdent_br
#print axioms RobinCaps.ThinDomain.arcTraceSt_br
#print axioms RobinCaps.Cap.capPoincare_one
#print axioms RobinCaps.Cap.sliceAC_transverse_cap_po
#print axioms RobinCaps.ThinDomain.traceIneqInput_hemisphere_bti
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_m1
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_m1
#print axioms RobinCaps.ThinDomain.capTraceMatch_of_sphere_cm
#print axioms RobinCaps.ThinDomain.lintegral_halfSphere_cm
#print axioms RobinCaps.Cap.capTraceDataHemi_th
#print axioms RobinCaps.Cap.capTraceDataHemi_bdΓ_eq_th
#print axioms RobinCaps.Cap.integrable_gammaTrace_sq_th
#print axioms RobinCaps.Cap.capEntranceL2_hemi_el
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_final
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_final
#print axioms RobinCaps.ThinDomain.trial_energy_field_tg
#print axioms RobinCaps.ThinDomain.bdSliceable_bdR_bsg
#print axioms RobinCaps.Cap.capPoincare_hemi_phg
#print axioms RobinCaps.Cap.truncatedSemi_beta_div_expansion
#print axioms RobinCaps.Domain.hemisphere_beta_eq_beta0
#print axioms RobinCaps.Domain.counterexample_of_asymptotics_diam'
#print axioms RobinCaps.Cap.append_F
#print axioms RobinCaps.Domain.volume_thinDomain
#print axioms RobinCaps.Domain.convex_thinDomain
#print axioms RobinCaps.Domain.euclidDiam_thinDomain_hemisphere
#print axioms RobinCaps.Transverse.weighted_radial_poincare
#print axioms RobinCaps.Transverse.nuR_expansion
#print axioms RobinCaps.Transverse.transverse_gap_oneDim
#print axioms RobinCaps.Transverse.psiN_weak_eq_of_classical
#print axioms RobinCaps.Sobolev.ae_eq_const_add_integral
#print axioms RobinCaps.Sobolev.exists_h1_of_hasWeakDeriv
#print axioms RobinCaps.Sobolev.Weak.massQ_pos
#print axioms RobinCaps.ThinDomain.integral_ball_polar
#print axioms RobinCaps.ThinDomain.hasWeakGradP_classical
#print axioms RobinCaps.ThinDomain.massPQ_pos
#print axioms RobinCaps.ThinDomain.TransverseGroundState.energy_lower
#print axioms RobinCaps.ThinDomain.boundaryIntegral_one
#print axioms RobinCaps.ThinDomain.mass_split
#print axioms RobinCaps.ThinDomain.hasWeakGradP_tensor
#print axioms RobinCaps.ThinDomain.hasWeakGradP_of_piecewise
#print axioms RobinCaps.ThinDomain.HasWeakGradP.comp_affP
#print axioms RobinCaps.ThinDomain.counterexample_of_mainTheorem'
#print axioms RobinCaps.ThinDomain.mainTheorem_of_globalComparison
#print axioms RobinCaps.ThinDomain.hasWeakDeriv_axialCoeff
#print axioms RobinCaps.ThinDomain.massP_trialH1P
#print axioms RobinCaps.ThinDomain.massP_eq_sum
#print axioms RobinCaps.ThinDomain.boundaryEnergy_tensor_split_of_continuous'
#print axioms RobinCaps.Transverse.groundStateOne
#print axioms RobinCaps.Transverse.robinForm_ge_of_orth
#print axioms RobinCaps.Transverse.psiH1_target
#print axioms RobinCaps.Transverse.dR_target
#print axioms RobinCaps.Cap.axial_poincare_c1
#print axioms RobinCaps.ThinDomain.bulk_exact_separation
#print axioms RobinCaps.ThinDomain.bulk_gap_bound
#print axioms RobinCaps.ThinDomain.bulk_mass_split
#print axioms RobinCaps.ThinDomain.bulk_separation
#print axioms RobinCaps.Cap.sliceAC_axial_cap
#print axioms RobinCaps.Cap.entranceVal_spec
#print axioms RobinCaps.Cap.exists_h1_axialSlice
#print axioms RobinCaps.Cap.axial_poincare_weak
#print axioms RobinCaps.Domain.euclidDiam_thinDomain_bounds
#print axioms RobinCaps.Domain.le_euclidDiam_thinDomain
#print axioms RobinCaps.Domain.euclidDiam_thinDomain_le
#print axioms RobinCaps.ThinDomain.dirichletP_trialH1P
#print axioms RobinCaps.ThinDomain.bulkProj_surjective
#print axioms RobinCaps.ThinDomain.sliceACL_axial
#print axioms RobinCaps.ThinDomain.sliceACL_transverse
#print axioms RobinCaps.ThinDomain.sliceACL_transverse_thin
#print axioms RobinCaps.ThinDomain.sliceACL_axial_thin
#print axioms RobinCaps.ThinDomain.dirichletP_eq_sum
#print axioms RobinCaps.ThinDomain.boundaryIntegral_split
#print axioms RobinCaps.ThinDomain.boundaryEnergy_tensor_split
#print axioms RobinCaps.ThinDomain.integrableOn_lateralDensity_of_bounded
#print axioms RobinCaps.Cap.weighted_poincare_c1
#print axioms RobinCaps.Cap.capJ_one
#print axioms RobinCaps.Cap.axial_poincare_line
#print axioms RobinCaps.Transverse.groundStateOneReg
#print axioms RobinCaps.ThinDomain.interfaceTraceInput_gen_big
#print axioms RobinCaps.ThinDomain.interfaceTraceInput_one_of_gen_big
#print axioms RobinCaps.ThinDomain.mainTheorem_gm
#print axioms RobinCaps.ThinDomain.counterexample_gm
#print axioms RobinCaps.ThinDomain.mainTheorem_gen_ag'
#print axioms RobinCaps.ThinDomain.capLowerInput_gen_bcg
#print axioms RobinCaps.Sobolev.Weak.sphForm_eq_bdR_stf
#print axioms RobinCaps.Cap.capEntranceL2_hemi_elg
#print axioms RobinCaps.Cap.capEntranceL2_flat_elf
#print axioms RobinCaps.ThinDomain.capLowerInput_gen_bcw
#print axioms RobinCaps.ThinDomain.capLowerInput_gen_bcg_of_bcw
#print axioms RobinCaps.ThinDomain.exists_groundStateFamily_bdR_gsf
#print axioms RobinCaps.ThinDomain.trial_energy_field_taw
#print axioms RobinCaps.ThinDomain.capEnergyTermW_sub_beta_tw
#print axioms RobinCaps.ThinDomain.cap_boundary_expansion_tw
#print axioms RobinCaps.ThinDomain.transverseExpansionDataW_xg
#print axioms RobinCaps.ThinDomain.exists_nonneg_mean_xg
#print axioms RobinCaps.ThinDomain.integral_bulkDensity_tgb
#print axioms RobinCaps.ThinDomain.bulkDensity_integral_le_tgb
#print axioms RobinCaps.ThinDomain.sphFormEqBdR_bsf
#print axioms RobinCaps.ThinDomain.integral_bulkDensity_bsf
#print axioms RobinCaps.ThinDomain.mainTheorem_bridged_bg
#print axioms RobinCaps.ThinDomain.counterexample_bridged_bg
#print axioms RobinCaps.ThinDomain.traceDataGen_tgn
#print axioms RobinCaps.ThinDomain.traceSplit_tgn
#print axioms RobinCaps.Cap.capPoincare_flat_pf
#print axioms RobinCaps.ThinDomain.capTraceIntegrable_tgi
#print axioms RobinCaps.ThinDomain.continuousBoundaryIntegrable_tgi
#print axioms RobinCaps.ThinDomain.expW_sharp_xs
#print axioms RobinCaps.ThinDomain.bulkTraceInput_bbt
#print axioms RobinCaps.ThinDomain.trial_energy_field_tam
#print axioms RobinCaps.ThinDomain.capLowerInput_mixed_bcm
#print axioms RobinCaps.ThinDomain.capEnergyTermFlat_sub_beta_tbf
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_gen_mg
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_gen_mg
#print axioms RobinCaps.ThinDomain.traceDataAbs_tga
#print axioms RobinCaps.ThinDomain.traceSplit_tga
#print axioms RobinCaps.ThinDomain.bd_eq_tgn_tga
#print axioms RobinCaps.ThinDomain.capTraceIntegrableAbs_hemi_mi
#print axioms RobinCaps.ThinDomain.continuousBoundaryIntegrableAbs_mixed_mi
#print axioms RobinCaps.ThinDomain.mainTheorem_mixed_bridged_bm
#print axioms RobinCaps.ThinDomain.mainTheorem_mixed_bridged_alpha_bm
#print axioms RobinCaps.Cap.capTraceDataFlat_tf
#print axioms RobinCaps.Cap.capTraceDataFlat_bdΓ_eq_tf
#print axioms RobinCaps.ThinDomain.mainTheorem_single_ms
#print axioms RobinCaps.ThinDomain.mainTheorem_single_alpha_ms
#print axioms RobinCaps.Cap.capTraceIntegrableAbs_flat_tfd
#print axioms RobinCaps.Cap.flatLiftBd_tfd
#print axioms RobinCaps.ThinDomain.mainTheorem_single_msf
#print axioms RobinCaps.ThinDomain.mainTheorem_single_alpha_msf
#print axioms RobinCaps.Cap.transverseShortSliceBound_hemi_ssh
#print axioms RobinCaps.Cap.capEntranceL2_hemi_ssh
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_gen_final
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_gen_final
#print axioms RobinCaps.ThinDomain.mainTheorem_single_final
#print axioms RobinCaps.ThinDomain.mainTheorem_single_alpha_final
#print axioms RobinCaps.ThinDomain.second_order_expansion_gl
#print axioms RobinCaps.ThinDomain.gradient_leading_gl
#print axioms RobinCaps.ThinDomain.positive_gl
#print axioms RobinCaps.sharp_cap_inequality_final_top
#print axioms RobinCaps.mainTheorem_hemisphere_gen_final_top
#print axioms RobinCaps.counterexample_hemisphere_gen_final_top
#print axioms RobinCaps.mainTheorem_single_alpha_final_top
#print axioms RobinCaps.ThinDomain.bd_unique_tu
#print axioms RobinCaps.ThinDomain.lambdaThin_congr_tu
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_any_tu
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_any_tu
#print axioms RobinCaps.ThinDomain.mainTheorem_single_any_tu
#print axioms RobinCaps.Sobolev.exists_c1_h1_close_cd
#print axioms RobinCaps.ThinDomain.c1Dense_tuf
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_any_final
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_any_final
#print axioms RobinCaps.ThinDomain.mainTheorem_single_any_final
#print axioms RobinCaps.ThinDomain.TransverseGroundState.nu_eq_lam1
#print axioms RobinCaps.ThinDomain.mainTheorem_hemisphere_nb
#print axioms RobinCaps.ThinDomain.counterexample_hemisphere_nb
#print axioms RobinCaps.ThinDomain.mainTheorem_single_nb
#print axioms RobinCaps.ThinDomain.mainTheorem_single_alpha_nb
#print axioms RobinCaps.mainTheorem_hemisphere_top
#print axioms RobinCaps.counterexample_hemisphere_top
#print axioms RobinCaps.mainTheorem_single_alpha_top
#print axioms RobinCaps.Cap.sharp_cap_inequality_uc
#print axioms RobinCaps.Cap.beta_ge_beta0_uc
#print axioms RobinCaps.Cap.equality_iff_uc
#print axioms RobinCaps.Cap.equalityCharacterization_uc
#print axioms RobinCaps.Domain.beta_ge_hemisphere_beta_uc
#print axioms RobinCaps.equality_iff_final_top
#print axioms RobinCaps.Compact.exists_transverseGroundStateReg
#print axioms RobinCaps.Compact.hasTransverseGroundStateReg
#print axioms RobinCaps.Compact.nuStar_spec
#print axioms RobinCaps.Compact.picone_H1
#print axioms RobinCaps.Compact.psiReg_pos
#print axioms RobinCaps.Sobolev.PoincareConvex.poincare_wirtinger_convex_pcx
#print axioms RobinCaps.Cap.entrance_c1_bound_ec1
#print axioms RobinCaps.Cap.lateral_le_annulus_lintegral_ths
#print axioms RobinCaps.Cap.lateral_integral_le_tlg
#print axioms RobinCaps.Cap.convex_body_cg
#print axioms RobinCaps.ThinDomain.capEnergyTermGen_sub_beta_tbg
#print axioms RobinCaps.ThinDomain.capLowerInput_gen2_bg2
#print axioms RobinCaps.ThinDomain.trial_energy_field_ag2
#print axioms RobinCaps.ThinDomain.mainTheorem_gen2_bridged_bg3
#print axioms RobinCaps.ThinDomain.mainTheorem_general_nb_mgl
#print axioms RobinCaps.Cap.capPoincare_gen_pgn
#print axioms RobinCaps.Sobolev.exists_c1_h1_close_cap_cdn
#print axioms RobinCaps.Cap.capEntranceL2_gen_eg2
#print axioms RobinCaps.ThinDomain.capEntranceL2_gen_mgc
#print axioms RobinCaps.ThinDomain.mainTheorem_general_of_traceData_mgc
#print axioms RobinCaps.ThinDomain.mainTheorem_general_hemi_hemi_mgc
#print axioms RobinCaps.Cap.exists_slopeSplit_or_flat_ssp
#print axioms RobinCaps.Cap.exitVal_sq_integral_le_ttg
#print axioms RobinCaps.Cap.exitVal_eq_of_continuousOn_ttg
#print axioms RobinCaps.Cap.exitVal_spec_ttg
#print axioms RobinCaps.Cap.aestronglyMeasurable_lateralTraceGen_tl2
#print axioms RobinCaps.Cap.capTraceIntegrableAbs_ofFlat_tfc
#print axioms RobinCaps.Cap.capTraceDataGen_tdg
#print axioms RobinCaps.Cap.capTraceIntegrableAbs_gen_tdg
#print axioms RobinCaps.ThinDomain.exists_capTraceData_gf
#print axioms RobinCaps.ThinDomain.mainTheorem_general_nb
#print axioms RobinCaps.mainTheorem_general_top
#print axioms RobinCaps.ThinDomain.gap_length_tendsto_cg
#print axioms RobinCaps.ThinDomain.counterexample_of_beta_lt_cg
#print axioms RobinCaps.Cap.frustum_F_lt_omega_fr
#print axioms RobinCaps.Cap.frustum_beta_lt_fr
#print axioms RobinCaps.counterexample_of_beta_lt_top
#print axioms RobinCaps.counterexample_nearFlat_top
#print axioms RobinCaps.Cap.linearization_bound_lip_pf
#print axioms RobinCaps.Cap.perturbedFlat_beta_lt_pf
#print axioms RobinCaps.counterexample_perturbedFlat_top
#print axioms RobinCaps.Compact.gap_of_small
#print axioms RobinCaps.Cap.capsule_surface_volume_ratio
#print axioms RobinCaps.Compact.smoothConvSetEst_ses
#print axioms RobinCaps.Compact.smoothDilateSetEst_ses
#print axioms RobinCaps.Compact.approxEstimateCvx_acx
#print axioms RobinCaps.Compact.rellichL2_convex_rcx
#print axioms RobinCaps.Compact.rellichL2_convex_final
#print axioms RobinCaps.Compact.rellich_convex_final
#print axioms RobinCaps.ThinDomain.rellichP_thin_rth
#print axioms RobinCaps.ThinDomain.h1pComplete_h1c
#print axioms RobinCaps.ThinDomain.exists_finrank_H1PQ_inf
#print axioms RobinCaps.Spectrum.constrainedMin_cmin
#print axioms RobinCaps.Spectrum.eigenFamily_efam
#print axioms RobinCaps.ThinDomain.exists_eigenfunctions_eth
#print axioms RobinCaps.ThinDomain.minmax_robinSetting_eth
#print axioms RobinCaps.ThinDomain.rellichP_thinDomain_final
#print axioms RobinCaps.ThinDomain.exists_robin_eigenfunctions_final
#print axioms RobinCaps.rellich_thinDomain_top
#print axioms RobinCaps.robin_eigenfunctions_top
#print axioms RobinCaps.robin_eigenfunctions_two_top
#print axioms RobinCaps.ThinDomain.isRobinImage_unique_rop
#print axioms RobinCaps.ThinDomain.isRobinImage_symm_rop
#print axioms RobinCaps.ThinDomain.isRobinImage_eigen_iff_rop
#print axioms RobinCaps.ThinDomain.eigen_quotient_rop
#print axioms RobinCaps.Spectrum.weakEigen_eq_minmax_wsp
#print axioms RobinCaps.Spectrum.minmax_isWeakEigen_wsp
#print axioms RobinCaps.Spectrum.minmax_tendsto_atTop_wsp
#print axioms RobinCaps.lambdaThin_tendsto_top
#print axioms RobinCaps.robin_weakEigen_top
#print axioms RobinCaps.robin_operator_spectrum_top
#print axioms RobinCaps.Hausdorff.hausdorffVolume_hlin
#print axioms RobinCaps.Hausdorff.linearImage_hlin
#print axioms RobinCaps.Hausdorff.nearLinear_hnl
#print axioms RobinCaps.Hausdorff.areaFormula_har
#print axioms RobinCaps.Hausdorff.areaFormulaInj_agi
#print axioms RobinCaps.Hausdorff.aemeasurableFderivWithin_gam
#print axioms RobinCaps.Hausdorff.areaLintegralInj_gam
#print axioms RobinCaps.Hausdorff.hemiToSphereLintegral_alt
#print axioms RobinCaps.Hausdorff.hemiToSphere_scv
#print axioms RobinCaps.Hausdorff.hemiHausdorff_sch
#print axioms RobinCaps.Hausdorff.sphereHausdorff_shd
#print axioms RobinCaps.Hausdorff.latChart_hasFDerivAt_lch
#print axioms RobinCaps.Hausdorff.latChart_injOn_lch
#print axioms RobinCaps.Hausdorff.frontier_thinDomain_tfr
#print axioms RobinCaps.Hausdorff.frontier_thinDomainE_tfr
#print axioms RobinCaps.Hausdorff.hausdorff_diskL_lintegral_tfr
#print axioms RobinCaps.Hausdorff.hausdorff_diskR_lintegral_tfr
#print axioms RobinCaps.hausdorff_eq_smul_volume_top
#print axioms RobinCaps.areaFormula_C1_top
#print axioms RobinCaps.areaFormula_top
#print axioms RobinCaps.areaFormula_lintegral_top
#print axioms RobinCaps.sphere_hausdorff_top
#print axioms RobinCaps.Hausdorff.areaFormulaGen_agg
#print axioms RobinCaps.Hausdorff.latPiece_lintegral_lpc
#print axioms RobinCaps.Hausdorff.ae_hasDerivAt_profile_prg
#print axioms RobinCaps.Hausdorff.hausdorff_latChart_null_prg
#print axioms RobinCaps.Hausdorff.ofReal_lateralIntegral_prg
#print axioms RobinCaps.Hausdorff.lateral_hausdorff_core_lsf
#print axioms RobinCaps.Hausdorff.lateral_hausdorff_lsf
#print axioms RobinCaps.Hausdorff.boundaryHausdorff_bfin
#print axioms RobinCaps.areaFormula_general_top
#print axioms RobinCaps.boundaryIntegral_eq_hausdorff_top
#print axioms RobinCaps.Hausdorff.steinerCompact_stc
#print axioms RobinCaps.Hausdorff.steinerVolume_stv
#print axioms RobinCaps.Hausdorff.steinerDiam_std
#print axioms RobinCaps.Hausdorff.steinerSymm_sts
#print axioms RobinCaps.Hausdorff.isodiametric_iso
#print axioms RobinCaps.Hausdorff.hConstValue_hcv
#print axioms RobinCaps.Spectrum.selfAdjointCriterion_sac
#print axioms RobinCaps.Spectrum.laxMilgram_lmg
#print axioms RobinCaps.ThinDomain.robinLaxMilgram_lmg
#print axioms RobinCaps.ThinDomain.robinOp_symm_rlp
#print axioms RobinCaps.ThinDomain.robinOp_isSelfAdjoint_rlp
#print axioms RobinCaps.ThinDomain.robinOp_eigen_iff_rlp
#print axioms RobinCaps.isodiametric_top
#print axioms RobinCaps.hConst_eq_top
#print axioms RobinCaps.stdHausdorff_eq_volume_top
#print axioms RobinCaps.boundaryIntegral_eq_stdHausdorff_top
#print axioms RobinCaps.robin_selfAdjoint_top
#print axioms RobinCaps.robin_selfAdjoint_spectrum_top
EOF
lake env lean .axiomcheck.lean
rm -f .axiomcheck.lean
echo
echo "OK"
