import Mathlib
import RobinCaps.Basic

/-!
# Admissible end caps of revolution: definitions

This file sets up the *definitional* layer for the end-cap functional of
`sec:calibration` (`reference/robin_endcaps_corrected_en.tex`, line 251).

An admissible end cap of revolution in transverse dimension `m` is a convex body
`C ⊆ ℝ × ℝ^m` obtained by rotating a concave, non-increasing profile `θ : ℝ → ℝ`
with `θ > 0`, `θ ≤ 1` on `(-K,0)` and `θ(-K⁺) = 1` around the axial direction.

The exposed boundary is `Γ = ∂C \ closure Σ`, where `Σ = {-K} × B_m(1)` is the
entrance disk.  The paper's functional is `𝓕(C) = ℋ^m(Γ) - m |C|`.

To keep the later computations concrete and honest we *also* define the explicit
revolution functional (`lateralArea`, `terminalArea`, `revolutionVolume`,
`revolutionF`) obtained by the classical surface/volume-of-revolution integrals.
The paper's functional `F` is *defined* as this explicit functional (see the
docstring of `F` for why mathlib's `hausdorffMeasure` is not the right object).

## Conventions
* ambient space: `ℝ × EuclideanSpace ℝ (Fin m)`;
* `volume` is the standard Lebesgue measure;
* `n = m + 1`.
-/

open MeasureTheory Set Filter
open scoped Topology

namespace RobinCaps

noncomputable section

/-- Ambient space of an end cap: axial coordinate times transverse space. -/
abbrev CapSpace (m : ℕ) : Type := ℝ × EuclideanSpace ℝ (Fin m)

/-- An **admissible end cap of revolution** for transverse dimension `m`.

The profile `θ` is defined on all of `ℝ`: only its values on `[-K,0]` matter, and the two
endpoint values are fixed by convention to be the one-sided limits (`θ_entrance`,
`θ_terminal`), so every profile of the manuscript is represented by exactly one `Cap`;
`K > 0` is the axial length.  The conditions are exactly those of
`eq:cap-definition` of the manuscript. -/
structure Cap (m : ℕ) where
  /-- Axial length of the cap. -/
  K : ℝ
  /-- Positivity of the axial length. -/
  hK : 0 < K
  /-- Radial profile. -/
  θ : ℝ → ℝ
  /-- The profile is positive on `(-K,0)`. -/
  θ_pos : ∀ s ∈ Set.Ioo (-K) 0, 0 < θ s
  /-- The profile is bounded above by `1`. -/
  θ_le_one : ∀ s ∈ Set.Ioo (-K) 0, θ s ≤ 1
  /-- The profile is concave. -/
  θ_concave : ConcaveOn ℝ (Set.Ioo (-K) 0) θ
  /-- The profile is non-increasing. -/
  θ_antitone : AntitoneOn θ (Set.Ioo (-K) 0)
  /-- The profile tends to `1` at the entrance `s = -K`. -/
  θ_tendsto : Filter.Tendsto θ (𝓝[>] (-K)) (𝓝 1)
  /-- Storage convention at the entrance: the recorded value is the limit, `θ(-K) = θ(-K⁺) = 1`. -/
  θ_entrance : θ (-K) = 1
  /-- Storage convention at the terminal point: the recorded value `θ(0)` is the manuscript's
  terminal radius `θ(0⁻)` (the left limit, which exists since `θ` is monotone and bounded). -/
  θ_terminal : Filter.Tendsto θ (𝓝[<] 0) (𝓝 (θ 0))

namespace Cap

variable {m : ℕ}

/-- The body `C = {(s,z) | -K < s < 0, ‖z‖ < θ s}` of the cap. -/
def body (C : Cap m) : Set (CapSpace m) :=
  {p | -C.K < p.1 ∧ p.1 < 0 ∧ ‖p.2‖ < C.θ p.1}

/-- The entrance disk `Σ = {-K} × B_m(1)`. -/
def Sigma (C : Cap m) : Set (CapSpace m) :=
  {p | p.1 = -C.K ∧ ‖p.2‖ < 1}

/-- The exposed boundary `Γ = ∂C \ closure Σ`.

If `θ(0) > 0` the terminal disk at `s = 0` belongs to `Γ`
(manuscript `eq:boundary-parts`). -/
def Gamma (C : Cap m) : Set (CapSpace m) :=
  frontier C.body \ closure C.Sigma

/-! ### Explicit revolution functional

The classical area/volume-of-revolution formulas.  For a profile `θ` on `(-K,0)`
and transverse dimension `m`:

* lateral surface area `m ω_m ∫ θ^{m-1} √(1+θ'²)`,
* terminal disk area `ω_m θ(0)^m`,
* body volume `ω_m ∫ θ^m`.

The terminal disk is included in the exposed boundary, as required by the
manuscript. -/

/-- Lateral surface area of the surface of revolution generated by `θ`. -/
noncomputable def lateralArea (C : Cap m) : ℝ :=
  (m : ℝ) * omega m *
    ∫ s in (-C.K)..0, (C.θ s) ^ (m - 1) * Real.sqrt (1 + (deriv C.θ s) ^ 2)

/-- Area of the terminal disk at `s = 0`, of radius `θ(0)`. -/
noncomputable def terminalArea (C : Cap m) : ℝ :=
  omega m * (C.θ 0) ^ m

/-- Total exposed surface area `|Γ|` (lateral plus terminal disk). -/
noncomputable def revolutionArea (C : Cap m) : ℝ :=
  C.lateralArea + C.terminalArea

/-- Body volume `|C|` by the volume-of-revolution formula. -/
noncomputable def revolutionVolume (C : Cap m) : ℝ :=
  omega m * ∫ s in (-C.K)..0, (C.θ s) ^ m

/-- The explicit functional `|Γ| - m |C|`. -/
noncomputable def revolutionF (C : Cap m) : ℝ :=
  C.revolutionArea - (m : ℝ) * C.revolutionVolume

/-- **The paper's functional** `𝓕(C) = ℋ^m(Γ) − m|C|` (manuscript `eq:beta-definition`).

For a body of revolution the `m`-dimensional surface measure of the exposed
boundary `Γ` (lateral surface plus terminal disk) is given by the classical
area formula `m ω_m ∫ θ^{m-1}√(1+θ'²) + ω_m θ(0)^m`, and `|C| = ω_m ∫ θ^m`
(the latter is *proved* to be the Lebesgue measure of `body`, see
`RobinCaps/Cap/Volume.lean`).  We therefore *define* `F` as the explicit
revolution functional.

**Why not mathlib's `hausdorffMeasure`?**  mathlib's `μH[d]` carries no
normalisation constant (`Σ diam^d` without the factor `ω_d/2^d`), so even in a
Euclidean space `μH[m]` of an `m`-surface is `2^m/ω_m` times its area; moreover
the ambient product type `ℝ × EuclideanSpace ℝ (Fin m)` carries the sup metric,
under which e.g. the unit semicircle (`m = 1`) has `μH[1]`-length `2√2 ≠ π`.
The former definition `hausdorffMeasure m Γ` was therefore **not** the
manuscript's `ℋ^m(Γ)` (it even violated the sharp inequality for the
hemisphere), and the bridge `F = revolutionF` recorded earlier was false.
The identification of this formula with the integral against the (normalised) Hausdorff measure is proved in `RobinCaps/Hausdorff/Wave13Final.lean` (`boundaryIntegral_eq_stdHausdorff_top`); earlier development stages did not use `hausdorffMeasure`. -/
noncomputable def F (C : Cap m) : ℝ := C.revolutionF

theorem F_eq_revolutionF (C : Cap m) : C.F = C.revolutionF := rfl

/-- The effective end coefficient `β(C) = (α/ω_m) 𝓕(C)`. -/
noncomputable def beta (C : Cap m) (alpha : ℝ) : ℝ :=
  alpha / omega m * C.F

/-! ### The flat cap `θ ≡ 1` -/

/-- The flat cap: profile `θ ≡ 1`, i.e. a straight cylinder segment of length `K`
with a flat terminal disk. -/
def flat (m : ℕ) (K : ℝ) (hK : 0 < K) : Cap m where
  K := K
  hK := hK
  θ := fun _ => 1
  θ_pos := by intro s hs; norm_num
  θ_le_one := by intro s hs; norm_num
  θ_concave := concaveOn_const 1 (convex_Ioo _ _)
  θ_antitone := antitoneOn_const
  θ_tendsto := tendsto_const_nhds
  θ_entrance := rfl
  θ_terminal := tendsto_const_nhds

/-! ### The truncated semicircular profile (only for `m = 1`) -/

/-- The upper semicircular profile `s ↦ √(1 - (s+K)²)`. -/
noncomputable def semi (K s : ℝ) : ℝ := Real.sqrt (1 - (s + K) ^ 2)

/-- Derivative of `semi K`, written as `-(s+K) * (√(1-(s+K)²))⁻¹`. -/
noncomputable def semiD (K s : ℝ) : ℝ :=
  -(s + K) * (Real.sqrt (1 - (s + K) ^ 2))⁻¹

/-- Second derivative of `semi K`. -/
noncomputable def semiD2 (K s : ℝ) : ℝ :=
  -1 / (Real.sqrt (1 - (s + K) ^ 2)) ^ 3

/-- First derivative of the semicircular profile on its interval of smoothness. -/
theorem semi_hasDerivAt (K : ℝ) {s : ℝ} (hs : 0 < 1 - (s + K) ^ 2) :
    HasDerivAt (semi K) (semiD K s) s := by
  have h1 : HasDerivAt (fun s : ℝ => 1 - (s + K) ^ 2) (-2 * (s + K)) s := by
    have h : HasDerivAt (fun s : ℝ => (s + K) ^ 2) (2 * (s + K)) s := by
      have h1 : HasDerivAt (fun s : ℝ => s + K) 1 s := (hasDerivAt_id s).add_const K
      simpa using h1.pow 2
    simpa using (hasDerivAt_const (x := s) (c := (1 : ℝ))).sub h
  have h2 : HasDerivAt Real.sqrt (1 / (2 * Real.sqrt (1 - (s + K) ^ 2)))
      (1 - (s + K) ^ 2) :=
    Real.hasDerivAt_sqrt (ne_of_gt hs)
  have h := h2.comp s h1
  have hval : (1 / (2 * Real.sqrt (1 - (s + K) ^ 2))) * (-2 * (s + K)) = semiD K s := by
    simp only [semiD]
    field_simp
  have hfun : (Real.sqrt ∘ fun s : ℝ => 1 - (s + K) ^ 2) = semi K := by
    funext t; simp [semi]
  rw [hfun] at h
  exact h.congr_deriv hval

/-- `deriv` of the semicircular profile. -/
theorem deriv_semi (K : ℝ) {s : ℝ} (hs : 0 < 1 - (s + K) ^ 2) :
    deriv (semi K) s = semiD K s := (semi_hasDerivAt K hs).deriv

/-- Second derivative of the semicircular profile. -/
theorem semiD_hasDerivAt (K : ℝ) {s : ℝ} (hs : 0 < 1 - (s + K) ^ 2) :
    HasDerivAt (semiD K) (semiD2 K s) s := by
  set u : ℝ → ℝ := fun s => 1 - (s + K) ^ 2 with hu
  have hv : HasDerivAt (fun s => Real.sqrt (u s)) (semiD K s) s := by
    have := semi_hasDerivAt K hs
    have hfun : (fun s => Real.sqrt (u s)) = semi K := by funext t; simp [semi, hu]
    rwa [hfun]
  have hv_ne : Real.sqrt (u s) ≠ 0 := ne_of_gt (Real.sqrt_pos.2 hs)
  have hnum : HasDerivAt (fun s : ℝ => -(s + K)) (-1) s := by
    have h := (hasDerivAt_id s).add_const K
    exact h.neg
  have hinv : HasDerivAt (fun s => (Real.sqrt (u s))⁻¹)
      (- semiD K s / (Real.sqrt (u s)) ^ 2) s := hv.inv hv_ne
  have hprod := hnum.mul hinv
  have hval : (-1) * (Real.sqrt (u s))⁻¹
      + (-(s + K)) * (- semiD K s / (Real.sqrt (u s)) ^ 2) = semiD2 K s := by
    simp only [semiD, semiD2, hu]
    have hs_ne : Real.sqrt (1 - (s + K) ^ 2) ≠ 0 := ne_of_gt (Real.sqrt_pos.2 hs)
    have hsq : (Real.sqrt (1 - (s + K) ^ 2)) ^ 2 = 1 - (s + K) ^ 2 :=
      Real.sq_sqrt (le_of_lt hs)
    field_simp
    rw [hsq]
    ring
  have hcongr : (fun s => -(s + K)) * (fun s => (Real.sqrt (u s))⁻¹) = semiD K := by
    funext t; simp only [Pi.mul_apply, semiD, hu]
  rw [hcongr] at hprod
  exact hprod.congr_deriv hval

section AdmissibleProfile

theorem semi_pos (K : ℝ) (hK1 : K ≤ 1) {s : ℝ} (hs : s ∈ Set.Ioo (-K) 0) :
    0 < semi K s := by
  have hs1 : s + K < 1 := by linarith [hs.2, hK1]
  have hinner : 0 < 1 - (s + K) ^ 2 := by nlinarith [hs.1, hs1]
  exact Real.sqrt_pos.2 hinner

theorem semi_le_one (K : ℝ) (hK1 : K ≤ 1) {s : ℝ} (hs : s ∈ Set.Ioo (-K) 0) :
    semi K s ≤ 1 := by
  have hinner : 0 ≤ 1 - (s + K) ^ 2 := by
    have hs1 : s + K < 1 := by linarith [hs.2, hK1]
    nlinarith [hs.1, hs1]
  have h2 : 1 - (s + K) ^ 2 ≤ 1 := by nlinarith
  calc semi K s = Real.sqrt (1 - (s + K) ^ 2) := rfl
    _ ≤ Real.sqrt 1 := Real.sqrt_le_sqrt h2
    _ = 1 := Real.sqrt_one

theorem semi_antitoneOn (K : ℝ) : AntitoneOn (semi K) (Set.Ioo (-K) 0) := by
  intro a ha b hb hab
  have ha1 : 0 < a + K := by linarith [ha.1]
  have hsq : (a + K) ^ 2 ≤ (b + K) ^ 2 := by nlinarith [ha1, hab]
  have hinner : 1 - (b + K) ^ 2 ≤ 1 - (a + K) ^ 2 := by linarith
  exact Real.sqrt_le_sqrt hinner

theorem semi_concaveOn (K : ℝ) (hK1 : K ≤ 1) :
    ConcaveOn ℝ (Set.Ioo (-K) 0) (semi K) := by
  refine concaveOn_of_hasDerivWithinAt2_nonpos (D := Set.Ioo (-K) 0) (f := semi K)
    (f' := semiD K) (f'' := semiD2 K) (convex_Ioo _ _) ?_ ?_ ?_ ?_
  · apply ContinuousOn.sqrt
    fun_prop
  · intro x hx
    rw [interior_Ioo] at hx
    have hpos : 0 < 1 - (x + K) ^ 2 := by
      have hx1 : x + K < 1 := by linarith [hx.2, hK1]
      nlinarith [hx.1, hx1]
    exact (semi_hasDerivAt K hpos).hasDerivWithinAt
  · intro x hx
    rw [interior_Ioo] at hx
    have hpos : 0 < 1 - (x + K) ^ 2 := by
      have hx1 : x + K < 1 := by linarith [hx.2, hK1]
      nlinarith [hx.1, hx1]
    exact (semiD_hasDerivAt K hpos).hasDerivWithinAt
  · intro x hx
    rw [interior_Ioo] at hx
    have hpos : 0 < 1 - (x + K) ^ 2 := by
      have hx1 : x + K < 1 := by linarith [hx.2, hK1]
      nlinarith [hx.1, hx1]
    simp only [semiD2]
    apply div_nonpos_of_nonpos_of_nonneg
    · norm_num
    · positivity

theorem semi_continuous (K : ℝ) : Continuous (semi K) := by
  apply Continuous.sqrt
  fun_prop

theorem semi_neg_self (K : ℝ) : semi K (-K) = 1 := by
  simp only [semi]
  rw [show -K + K = (0 : ℝ) by ring, zero_pow (by norm_num), sub_zero, Real.sqrt_one]

theorem semi_tendsto_left (K a : ℝ) : Tendsto (semi K) (𝓝[<] a) (𝓝 (semi K a)) :=
  ((semi_continuous K).tendsto a).mono_left nhdsWithin_le_nhds

theorem semi_tendsto (K : ℝ) : Tendsto (semi K) (𝓝[>] (-K)) (𝓝 1) := by
  have hcont : Continuous (semi K) := by
    apply Continuous.sqrt
    fun_prop
  have h := hcont.tendsto (-K)
  have hval : semi K (-K) = 1 := by
    simp only [semi]
    rw [show -K + K = (0 : ℝ) by ring, zero_pow (by norm_num), sub_zero, Real.sqrt_one]
  rw [hval] at h
  exact h.mono_left inf_le_left

end AdmissibleProfile

/-- The truncated semicircular cap of transverse dimension `1`.

For `0 ≤ γ < 1`, `K_γ = √(1-γ²)` and `θ_γ(s) = √(1-(s+K_γ)²)` for `s ∈ (-K_γ,0)`.
The entrance radius is `1` and the terminal radius is `γ`. -/
noncomputable def truncatedSemi (γ : ℝ) (hγ : 0 ≤ γ) (hγ1 : γ < 1) : Cap 1 where
  K := Real.sqrt (1 - γ ^ 2)
  hK := by
    rw [Real.sqrt_pos]
    nlinarith
  θ := semi (Real.sqrt (1 - γ ^ 2))
  θ_pos := fun s hs => semi_pos _ (by rw [Real.sqrt_le_one]; nlinarith) hs
  θ_le_one := fun s hs => semi_le_one _ (by rw [Real.sqrt_le_one]; nlinarith) hs
  θ_concave := semi_concaveOn _ (by rw [Real.sqrt_le_one]; nlinarith)
  θ_antitone := semi_antitoneOn _
  θ_tendsto := semi_tendsto _
  θ_entrance := semi_neg_self _
  θ_terminal := semi_tendsto_left _ 0

end Cap

end

end RobinCaps
