import Mathlib
import RobinCaps.Cap.Basic
import RobinCaps.Cap.Volume
import RobinCaps.Cap.Concave
import RobinCaps.Cap.Sharp

/-!
# The thin domain `Ω_R`

This file defines the thin domain of the manuscript
(`reference/robin_endcaps_corrected_en.tex`, `eq:profile`, `eq:domain`) and
proves its basic geometric and measure-theoretic properties.

With total axial span `L` and end caps `C₋`, `C₊` of axial lengths `K₋`, `K₊`,
the domain is the solid of revolution generated by the radial profile

`r_R(x) = R θ₋((-L/2 - x)/R)` for `-L/2 < x < -L/2 + K₋ R` (left cap),
`r_R(x) = R`                  for `-L/2 + K₋ R ≤ x ≤ L/2 - K₊ R` (bulk),
`r_R(x) = R θ₊((x - L/2)/R)`  for `L/2 - K₊ R < x < L/2` (right cap),

namely `Ω_R = {(x,z) : -L/2 < x < L/2, ‖z‖ < r_R(x)}`.

## Main results

* `profile_left`, `profile_bulk`, `profile_right`: the three branches;
* `profile_pos`, `profile_le_R`: `0 < r_R ≤ R` on `(-L/2, L/2)`;
* `continuousOn_profile`: `r_R` is continuous on `(-L/2, L/2)` (at the two
  interfaces this uses `Cap.θ_tendsto`, since the *value* of `θ` at `-K` is
  not constrained by the `Cap` structure — only its limit is);
* `isOpen_thinDomain`, `isBounded_thinDomain`, `thinDomain_nonempty`;
* `thinDomain_eq_union`: the bulk–cap decomposition, with the caps the images
  of `C.body` under `(s,z) ↦ (-L/2 - R s, R z)` and `(s,z) ↦ (L/2 + R s, R z)`;
* `volume_thinDomain`:
  `|Ω_R| = ω_m R^m ℓ_R + R^{m+1} (|C₋| + |C₊|)` with `ℓ_R = L - (K₋+K₊) R`;
* `mem_thinDomain_hemisphere_iff`: for two hemispherical caps `Ω_R` is the
  Euclidean capsule `{X : dist(X, S_R) < R}` around the axial segment
  `S_R = [-(L/2-R), L/2-R] × {0}`.

The convexity of `Ω_R` (manuscript, after `eq:domain`) is proved in
`Domain/ThinConvex.lean` (`convex_thinDomain`), not here.
-/

open MeasureTheory Set Filter Metric
open scoped Topology ENNReal

namespace RobinCaps
namespace Domain

open RobinCaps.Cap

noncomputable section

variable {m : ℕ}

/-! ## Definitions -/

/-- The radial profile `r_R` of the thin domain (manuscript `eq:profile`,
with `a = -L/2`, `b = L/2`). -/
def profile (Cm Cp : Cap m) (L R : ℝ) (x : ℝ) : ℝ :=
  if x < -L/2 + Cm.K * R then R * Cm.θ ((-L/2 - x) / R)
  else if x ≤ L/2 - Cp.K * R then R
  else R * Cp.θ ((x - L/2) / R)

/-- The thin domain `Ω_R` (manuscript `eq:domain`). -/
def thinDomain (Cm Cp : Cap m) (L R : ℝ) : Set (CapSpace m) :=
  {p | -L/2 < p.1 ∧ p.1 < L/2 ∧ ‖p.2‖ < profile Cm Cp L R p.1}

/-- The bulk length `ℓ_R = L - (K₋ + K₊) R` (manuscript `eq:bulk-interval`). -/
def bulkLength (Cm Cp : Cap m) (L R : ℝ) : ℝ := L - (Cm.K + Cp.K) * R

/-- The image of the left cap body under `(s,z) ↦ (-L/2 - R s, R z)`. -/
def leftCap (Cm : Cap m) (L R : ℝ) : Set (CapSpace m) :=
  (fun p : CapSpace m => ((-L/2 - R * p.1 : ℝ), R • p.2)) '' Cm.body

/-- The image of the right cap body under `(s,z) ↦ (L/2 + R s, R z)`. -/
def rightCap (Cp : Cap m) (L R : ℝ) : Set (CapSpace m) :=
  (fun p : CapSpace m => ((L/2 + R * p.1 : ℝ), R • p.2)) '' Cp.body

/-- The (closed) cylindrical bulk `[x₋, x₊] × B_m(R)`.  The closed axial
interval is used so that the decomposition `thinDomain_eq_union` is an exact
set equality: the two interface disks belong to `Ω_R`. -/
def bulkCylinder (Cm Cp : Cap m) (L R : ℝ) : Set (CapSpace m) :=
  Icc (-L/2 + Cm.K * R) (L/2 - Cp.K * R) ×ˢ ball (0 : EuclideanSpace ℝ (Fin m)) R

variable {Cm Cp : Cap m} {L R : ℝ}

/-! ## Unfolding lemmas -/

theorem profile_left {x : ℝ} (hx : x < -L/2 + Cm.K * R) :
    profile Cm Cp L R x = R * Cm.θ ((-L/2 - x) / R) := by
  simp only [profile]
  rw [if_pos hx]

theorem profile_bulk {x : ℝ} (h1 : -L/2 + Cm.K * R ≤ x) (h2 : x ≤ L/2 - Cp.K * R) :
    profile Cm Cp L R x = R := by
  simp only [profile]
  rw [if_neg (not_lt.2 h1), if_pos h2]

theorem profile_right {x : ℝ} (h1 : -L/2 + Cm.K * R ≤ x) (h2 : L/2 - Cp.K * R < x) :
    profile Cm Cp L R x = R * Cp.θ ((x - L/2) / R) := by
  simp only [profile]
  rw [if_neg (not_lt.2 h1), if_neg (not_le.2 h2)]

/-! ## Elementary consequences of admissibility -/

/-- The two interfaces are ordered: `x₋ < x₊`. -/
theorem interface_lt (_hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    -L/2 + Cm.K * R < L/2 - Cp.K * R := by
  have h := add_mul Cm.K Cp.K R
  linarith

theorem left_lt_interface (hR : 0 < R) : -L/2 < -L/2 + Cm.K * R := by
  have := mul_pos Cm.hK hR; linarith

theorem interface_lt_right (hR : 0 < R) : L/2 - Cp.K * R < L/2 := by
  have := mul_pos Cp.hK hR; linarith

theorem span_pos (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) : 0 < L := by
  have h1 : 0 < Cm.K + Cp.K := by linarith [Cm.hK, Cp.hK]
  have := mul_pos h1 hR
  linarith

/-- The left reparametrisation maps the left cap interval into `(-K₋, 0)`. -/
theorem left_param_mem (hR : 0 < R) {x : ℝ} (hx : x ∈ Ioo (-L/2) (-L/2 + Cm.K * R)) :
    (-L/2 - x) / R ∈ Ioo (-Cm.K) 0 := by
  obtain ⟨h1, h2⟩ := hx
  constructor
  · rw [lt_div_iff₀ hR]; nlinarith
  · rw [div_lt_iff₀ hR]; nlinarith

/-- The right reparametrisation maps the right cap interval into `(-K₊, 0)`. -/
theorem right_param_mem (hR : 0 < R) {x : ℝ} (hx : x ∈ Ioo (L/2 - Cp.K * R) (L/2)) :
    (x - L/2) / R ∈ Ioo (-Cp.K) 0 := by
  obtain ⟨h1, h2⟩ := hx
  constructor
  · rw [lt_div_iff₀ hR]; nlinarith
  · rw [div_lt_iff₀ hR]; nlinarith

/-! ## Positivity and the upper bound `r_R ≤ R` -/

theorem profile_pos (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) {x : ℝ}
    (hx : x ∈ Ioo (-L/2) (L/2)) : 0 < profile Cm Cp L R x := by
  rcases lt_or_ge x (-L/2 + Cm.K * R) with h | h
  · rw [profile_left h]
    exact mul_pos hR (Cm.θ_pos _ (left_param_mem hR ⟨hx.1, h⟩))
  · rcases le_or_gt x (L/2 - Cp.K * R) with h' | h'
    · rw [profile_bulk h h']; exact hR
    · rw [profile_right h h']
      exact mul_pos hR (Cp.θ_pos _ (right_param_mem hR ⟨h', hx.2⟩))

theorem profile_le_R (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) {x : ℝ}
    (hx : x ∈ Ioo (-L/2) (L/2)) : profile Cm Cp L R x ≤ R := by
  rcases lt_or_ge x (-L/2 + Cm.K * R) with h | h
  · rw [profile_left h]
    have := Cm.θ_le_one _ (left_param_mem hR ⟨hx.1, h⟩)
    nlinarith
  · rcases le_or_gt x (L/2 - Cp.K * R) with h' | h'
    · rw [profile_bulk h h']
    · rw [profile_right h h']
      have := Cp.θ_le_one _ (right_param_mem hR ⟨h', hx.2⟩)
      nlinarith

/-! ## Continuity of the profile -/

theorem continuousOn_profile_left (hR : 0 < R) :
    ContinuousOn (fun x : ℝ => R * Cm.θ ((-L/2 - x) / R))
      (Ioo (-L/2) (-L/2 + Cm.K * R)) := by
  have hcomp : ContinuousOn (fun x : ℝ => Cm.θ ((-L/2 - x) / R))
      (Ioo (-L/2) (-L/2 + Cm.K * R)) :=
    (Concave.continuousOn_Ioo Cm).comp (by fun_prop) (fun x hx => left_param_mem hR hx)
  exact continuousOn_const.mul hcomp

theorem continuousOn_profile_right (hR : 0 < R) :
    ContinuousOn (fun x : ℝ => R * Cp.θ ((x - L/2) / R))
      (Ioo (L/2 - Cp.K * R) (L/2)) := by
  have hcomp : ContinuousOn (fun x : ℝ => Cp.θ ((x - L/2) / R))
      (Ioo (L/2 - Cp.K * R) (L/2)) :=
    (Concave.continuousOn_Ioo Cp).comp (by fun_prop) (fun x hx => right_param_mem hR hx)
  exact continuousOn_const.mul hcomp

/-- Continuity at the left interface: the one-sided limit from the cap side is
`R` by `Cap.θ_tendsto`, and the profile is constantly `R` on the bulk side. -/
theorem continuousAt_profile_left_interface (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    ContinuousAt (profile Cm Cp L R) (-L/2 + Cm.K * R) := by
  have hmid := interface_lt (Cm := Cm) (Cp := Cp) hR hL
  have hval : profile Cm Cp L R (-L/2 + Cm.K * R) = R := profile_bulk le_rfl hmid.le
  -- the reparametrisation tends to `-K₋` from the right
  have hgc : Continuous (fun x : ℝ => (-L/2 - x) / R) := by fun_prop
  have hg0 : (-L/2 - (-L/2 + Cm.K * R)) / R = -Cm.K := by
    field_simp
    ring
  have hg1 : Tendsto (fun x : ℝ => (-L/2 - x) / R)
      (𝓝[<] (-L/2 + Cm.K * R)) (𝓝 (-Cm.K)) := by
    rw [← hg0]
    exact (hgc.tendsto _).mono_left nhdsWithin_le_nhds
  have hg2 : ∀ᶠ x in 𝓝[<] (-L/2 + Cm.K * R), (-L/2 - x) / R ∈ Ioi (-Cm.K) := by
    filter_upwards [self_mem_nhdsWithin] with x hx
    have hx' : x < -L/2 + Cm.K * R := hx
    simp only [mem_Ioi, lt_div_iff₀ hR]
    nlinarith
  have hgw : Tendsto (fun x : ℝ => (-L/2 - x) / R)
      (𝓝[<] (-L/2 + Cm.K * R)) (𝓝[>] (-Cm.K)) :=
    tendsto_nhdsWithin_of_tendsto_nhds_of_eventually_within _ hg1 hg2
  have hleft : ContinuousWithinAt (profile Cm Cp L R) (Iio (-L/2 + Cm.K * R))
      (-L/2 + Cm.K * R) := by
    rw [ContinuousWithinAt, hval]
    have hEq : EqOn (fun x : ℝ => R * Cm.θ ((-L/2 - x) / R)) (profile Cm Cp L R)
        (Iio (-L/2 + Cm.K * R)) := fun y hy => (profile_left hy).symm
    refine Filter.Tendsto.congr' (Filter.eventuallyEq_of_mem self_mem_nhdsWithin hEq) ?_
    have := (tendsto_const_nhds (x := R) (f := 𝓝[<] (-L/2 + Cm.K * R))).mul
      (Cm.θ_tendsto.comp hgw)
    simpa using this
  have hright : ContinuousWithinAt (profile Cm Cp L R) (Ici (-L/2 + Cm.K * R))
      (-L/2 + Cm.K * R) := by
    rw [ContinuousWithinAt, hval]
    have hmem : Ico (-L/2 + Cm.K * R) (L/2 - Cp.K * R) ∈
        𝓝[Ici (-L/2 + Cm.K * R)] (-L/2 + Cm.K * R) :=
      mem_nhdsWithin.2 ⟨Iio (L/2 - Cp.K * R), isOpen_Iio, hmid,
        fun y hy => ⟨hy.2, hy.1⟩⟩
    have hEq : EqOn (fun _ : ℝ => R) (profile Cm Cp L R)
        (Ico (-L/2 + Cm.K * R) (L/2 - Cp.K * R)) :=
      fun y hy => (profile_bulk hy.1 hy.2.le).symm
    refine Filter.Tendsto.congr' (Filter.eventuallyEq_of_mem hmem hEq) ?_
    exact tendsto_const_nhds
  have hu := hleft.union hright
  rw [Iio_union_Ici] at hu
  exact continuousWithinAt_univ _ _ |>.1 hu

/-- Continuity at the right interface. -/
theorem continuousAt_profile_right_interface (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    ContinuousAt (profile Cm Cp L R) (L/2 - Cp.K * R) := by
  have hmid := interface_lt (Cm := Cm) (Cp := Cp) hR hL
  have hval : profile Cm Cp L R (L/2 - Cp.K * R) = R := profile_bulk hmid.le le_rfl
  have hgc : Continuous (fun x : ℝ => (x - L/2) / R) := by fun_prop
  have hg0 : ((L/2 - Cp.K * R) - L/2) / R = -Cp.K := by
    field_simp
    ring
  have hg1 : Tendsto (fun x : ℝ => (x - L/2) / R)
      (𝓝[>] (L/2 - Cp.K * R)) (𝓝 (-Cp.K)) := by
    rw [← hg0]
    exact (hgc.tendsto _).mono_left nhdsWithin_le_nhds
  have hg2 : ∀ᶠ x in 𝓝[>] (L/2 - Cp.K * R), (x - L/2) / R ∈ Ioi (-Cp.K) := by
    filter_upwards [self_mem_nhdsWithin] with x hx
    have hx' : L/2 - Cp.K * R < x := hx
    simp only [mem_Ioi, lt_div_iff₀ hR]
    nlinarith
  have hgw : Tendsto (fun x : ℝ => (x - L/2) / R)
      (𝓝[>] (L/2 - Cp.K * R)) (𝓝[>] (-Cp.K)) :=
    tendsto_nhdsWithin_of_tendsto_nhds_of_eventually_within _ hg1 hg2
  have hright : ContinuousWithinAt (profile Cm Cp L R) (Ioi (L/2 - Cp.K * R))
      (L/2 - Cp.K * R) := by
    rw [ContinuousWithinAt, hval]
    have hEq : EqOn (fun x : ℝ => R * Cp.θ ((x - L/2) / R)) (profile Cm Cp L R)
        (Ioi (L/2 - Cp.K * R)) := by
      intro y hy
      have hy' : L/2 - Cp.K * R < y := hy
      exact (profile_right (by linarith) hy').symm
    refine Filter.Tendsto.congr' (Filter.eventuallyEq_of_mem self_mem_nhdsWithin hEq) ?_
    have := (tendsto_const_nhds (x := R) (f := 𝓝[>] (L/2 - Cp.K * R))).mul
      (Cp.θ_tendsto.comp hgw)
    simpa using this
  have hleft : ContinuousWithinAt (profile Cm Cp L R) (Iic (L/2 - Cp.K * R))
      (L/2 - Cp.K * R) := by
    rw [ContinuousWithinAt, hval]
    have hmem : Ioc (-L/2 + Cm.K * R) (L/2 - Cp.K * R) ∈
        𝓝[Iic (L/2 - Cp.K * R)] (L/2 - Cp.K * R) :=
      mem_nhdsWithin.2 ⟨Ioi (-L/2 + Cm.K * R), isOpen_Ioi, hmid,
        fun y hy => ⟨hy.1, hy.2⟩⟩
    have hEq : EqOn (fun _ : ℝ => R) (profile Cm Cp L R)
        (Ioc (-L/2 + Cm.K * R) (L/2 - Cp.K * R)) :=
      fun y hy => (profile_bulk hy.1.le hy.2).symm
    refine Filter.Tendsto.congr' (Filter.eventuallyEq_of_mem hmem hEq) ?_
    exact tendsto_const_nhds
  have hu := hleft.union hright
  rw [Iic_union_Ioi] at hu
  exact continuousWithinAt_univ _ _ |>.1 hu

/-- **The profile is continuous on the axial interval `(-L/2, L/2)`.** -/
theorem continuousOn_profile (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    ContinuousOn (profile Cm Cp L R) (Ioo (-L/2) (L/2)) := by
  have hmid := interface_lt (Cm := Cm) (Cp := Cp) hR hL
  have hl := left_lt_interface (Cm := Cm) (L := L) hR
  have hr := interface_lt_right (Cp := Cp) (L := L) hR
  intro x hx
  rcases lt_trichotomy x (-L/2 + Cm.K * R) with hA | hA | hA
  · -- interior of the left cap
    have hcont : ContinuousOn (profile Cm Cp L R) (Ioo (-L/2) (-L/2 + Cm.K * R)) :=
      (continuousOn_profile_left hR).congr (fun y hy => profile_left hy.2)
    exact (hcont.continuousAt (isOpen_Ioo.mem_nhds ⟨hx.1, hA⟩)).continuousWithinAt
  · subst hA
    exact (continuousAt_profile_left_interface hR hL).continuousWithinAt
  · rcases lt_trichotomy x (L/2 - Cp.K * R) with hB | hB | hB
    · -- interior of the bulk
      have hconst : ContinuousOn (fun _ : ℝ => R)
          (Ioo (-L/2 + Cm.K * R) (L/2 - Cp.K * R)) := continuousOn_const
      have hcont : ContinuousOn (profile Cm Cp L R)
          (Ioo (-L/2 + Cm.K * R) (L/2 - Cp.K * R)) :=
        hconst.congr (fun y hy => profile_bulk hy.1.le hy.2.le)
      exact (hcont.continuousAt (isOpen_Ioo.mem_nhds ⟨hA, hB⟩)).continuousWithinAt
    · subst hB
      exact (continuousAt_profile_right_interface hR hL).continuousWithinAt
    · -- interior of the right cap
      have hcont : ContinuousOn (profile Cm Cp L R) (Ioo (L/2 - Cp.K * R) (L/2)) :=
        (continuousOn_profile_right hR).congr
          (fun y hy => profile_right (le_of_lt (lt_trans hmid hy.1)) hy.1)
      exact (hcont.continuousAt (isOpen_Ioo.mem_nhds ⟨hB, hx.2⟩)).continuousWithinAt

/-! ## Topological properties of `Ω_R` -/

/-- **The thin domain is open.** -/
theorem isOpen_thinDomain (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    IsOpen (thinDomain Cm Cp L R) := by
  have hU : IsOpen (Ioo (-L/2) (L/2) ×ˢ (univ : Set (EuclideanSpace ℝ (Fin m)))) :=
    isOpen_Ioo.prod isOpen_univ
  have hF : ContinuousOn (fun p : CapSpace m => (‖p.2‖, profile Cm Cp L R p.1))
      (Ioo (-L/2) (L/2) ×ˢ (univ : Set (EuclideanSpace ℝ (Fin m)))) := by
    refine ContinuousOn.prodMk continuous_snd.norm.continuousOn ?_
    exact (continuousOn_profile hR hL).comp continuous_fst.continuousOn (fun p hp => hp.1)
  have ht : IsOpen {q : ℝ × ℝ | q.1 < q.2} := isOpen_lt continuous_fst continuous_snd
  have h := hF.isOpen_inter_preimage hU ht
  convert h using 1
  ext p
  simp [thinDomain, and_assoc]

theorem measurableSet_thinDomain (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    MeasurableSet (thinDomain Cm Cp L R) := (isOpen_thinDomain hR hL).measurableSet

/-- **The thin domain is bounded**: it sits in `(-L/2, L/2) × B_m(R)`. -/
theorem isBounded_thinDomain (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    Bornology.IsBounded (thinDomain Cm Cp L R) := by
  have hsub : thinDomain Cm Cp L R ⊆
      Ioo (-L/2) (L/2) ×ˢ ball (0 : EuclideanSpace ℝ (Fin m)) R := by
    intro p hp
    exact ⟨⟨hp.1, hp.2.1⟩,
      mem_ball_zero_iff.2 (lt_of_lt_of_le hp.2.2 (profile_le_R hR hL ⟨hp.1, hp.2.1⟩))⟩
  exact Bornology.IsBounded.subset ((Metric.isBounded_Ioo _ _).prod Metric.isBounded_ball) hsub

/-- **The thin domain is nonempty**: the origin belongs to it. -/
theorem thinDomain_nonempty (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    (thinDomain Cm Cp L R).Nonempty := by
  have hL0 : 0 < L := span_pos (Cm := Cm) (Cp := Cp) hR hL
  refine ⟨(0, 0), by linarith, by linarith, ?_⟩
  simpa using profile_pos hR hL (show (0:ℝ) ∈ Ioo (-L/2) (L/2) from ⟨by linarith, by linarith⟩)

/-! ## The bulk–cap decomposition -/

theorem mem_leftCap_iff (hR : 0 < R) {q : CapSpace m} :
    q ∈ leftCap Cm L R ↔
      -L/2 < q.1 ∧ q.1 < -L/2 + Cm.K * R ∧ ‖q.2‖ < R * Cm.θ ((-L/2 - q.1) / R) := by
  constructor
  · rintro ⟨⟨s, z⟩, ⟨hs1, hs2, hz⟩, rfl⟩
    have hsR : (-L/2 - (-L/2 - R * s)) / R = s := by field_simp; ring
    refine ⟨by nlinarith, by nlinarith, ?_⟩
    simp only [hsR, norm_smul, Real.norm_eq_abs, abs_of_pos hR]
    exact mul_lt_mul_of_pos_left hz hR
  · rintro ⟨h1, h2, h3⟩
    refine ⟨((-L/2 - q.1) / R, R⁻¹ • q.2), ⟨?_, ?_, ?_⟩, ?_⟩
    · rw [lt_div_iff₀ hR]; nlinarith
    · rw [div_lt_iff₀ hR]; nlinarith
    · rw [norm_smul, Real.norm_eq_abs, abs_of_pos (inv_pos.2 hR), inv_mul_lt_iff₀ hR]
      exact h3
    · have h4 : -L/2 - R * ((-L/2 - q.1) / R) = q.1 := by field_simp; ring
      have h5 : R • (R⁻¹ • q.2) = q.2 := by
        rw [smul_smul, mul_inv_cancel₀ hR.ne', one_smul]
      simp only [h4, h5]

theorem mem_rightCap_iff (hR : 0 < R) {q : CapSpace m} :
    q ∈ rightCap Cp L R ↔
      L/2 - Cp.K * R < q.1 ∧ q.1 < L/2 ∧ ‖q.2‖ < R * Cp.θ ((q.1 - L/2) / R) := by
  constructor
  · rintro ⟨⟨s, z⟩, ⟨hs1, hs2, hz⟩, rfl⟩
    have hsR : ((L/2 + R * s) - L/2) / R = s := by field_simp; ring
    refine ⟨by nlinarith, by nlinarith, ?_⟩
    simp only [hsR, norm_smul, Real.norm_eq_abs, abs_of_pos hR]
    exact mul_lt_mul_of_pos_left hz hR
  · rintro ⟨h1, h2, h3⟩
    refine ⟨((q.1 - L/2) / R, R⁻¹ • q.2), ⟨?_, ?_, ?_⟩, ?_⟩
    · rw [lt_div_iff₀ hR]; nlinarith
    · rw [div_lt_iff₀ hR]; nlinarith
    · rw [norm_smul, Real.norm_eq_abs, abs_of_pos (inv_pos.2 hR), inv_mul_lt_iff₀ hR]
      exact h3
    · have h4 : L/2 + R * ((q.1 - L/2) / R) = q.1 := by field_simp; ring
      have h5 : R • (R⁻¹ • q.2) = q.2 := by
        rw [smul_smul, mul_inv_cancel₀ hR.ne', one_smul]
      simp only [h4, h5]

/-- **The bulk–cap decomposition** (manuscript, after `eq:domain`): the thin
domain is the union of the two affine images of the cap bodies and the closed
cylindrical bulk. -/
theorem thinDomain_eq_union (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    thinDomain Cm Cp L R = leftCap Cm L R ∪ bulkCylinder Cm Cp L R ∪ rightCap Cp L R := by
  have hmid := interface_lt (Cm := Cm) (Cp := Cp) hR hL
  have hl := left_lt_interface (Cm := Cm) (L := L) hR
  have hr := interface_lt_right (Cp := Cp) (L := L) hR
  ext q
  constructor
  · rintro ⟨h1, h2, h3⟩
    rcases lt_or_ge q.1 (-L/2 + Cm.K * R) with hA | hA
    · refine Or.inl (Or.inl ?_)
      rw [mem_leftCap_iff hR]
      exact ⟨h1, hA, by rwa [profile_left hA] at h3⟩
    · rcases le_or_gt q.1 (L/2 - Cp.K * R) with hB | hB
      · refine Or.inl (Or.inr ?_)
        refine ⟨⟨hA, hB⟩, mem_ball_zero_iff.2 ?_⟩
        rwa [profile_bulk hA hB] at h3
      · refine Or.inr ?_
        rw [mem_rightCap_iff hR]
        exact ⟨hB, h2, by rwa [profile_right hA hB] at h3⟩
  · rintro ((hq | hq) | hq)
    · rw [mem_leftCap_iff hR] at hq
      obtain ⟨h1, h2, h3⟩ := hq
      exact ⟨h1, by linarith, by rwa [profile_left h2]⟩
    · obtain ⟨⟨hA, hB⟩, hz⟩ := hq
      refine ⟨by linarith, by linarith, ?_⟩
      rw [profile_bulk hA hB]
      exact mem_ball_zero_iff.1 hz
    · rw [mem_rightCap_iff hR] at hq
      obtain ⟨h1, h2, h3⟩ := hq
      exact ⟨by linarith, h2, by rwa [profile_right (by linarith) h1]⟩

/-! ## The volume of `Ω_R` -/

/-- Interval integrals only see the open interval. -/
theorem integral_congr_Ioo {a b : ℝ} (hab : a ≤ b) {f g : ℝ → ℝ} (h : EqOn f g (Ioo a b)) :
    ∫ x in a..b, f x = ∫ x in a..b, g x := by
  rw [intervalIntegral.integral_of_le hab, intervalIntegral.integral_of_le hab,
    integral_Ioc_eq_integral_Ioo, integral_Ioc_eq_integral_Ioo]
  exact setIntegral_congr_fun measurableSet_Ioo h

/-- Substitution `x = -L/2 - R s` on the left cap interval. -/
theorem integral_comp_left (K R L : ℝ) (hR : R ≠ 0) (f : ℝ → ℝ) :
    ∫ x in (-L/2)..(-L/2 + K * R), f ((-L/2 - x) / R) = R * ∫ s in (-K)..(0:ℝ), f s := by
  have h : ∀ x : ℝ, (-L/2 - x) / R = (-L/2) / R - x / R := fun x => sub_div _ _ _
  simp only [h]
  rw [intervalIntegral.integral_comp_sub_div f hR ((-L/2) / R),
    show (-L/2) / R - (-L/2 + K * R) / R = -K by field_simp; ring,
    show (-L/2) / R - (-L/2) / R = (0:ℝ) by ring, smul_eq_mul]

/-- Substitution `x = L/2 + R s` on the right cap interval. -/
theorem integral_comp_right (K R L : ℝ) (hR : R ≠ 0) (f : ℝ → ℝ) :
    ∫ x in (L/2 - K * R)..(L/2), f ((x - L/2) / R) = R * ∫ s in (-K)..(0:ℝ), f s := by
  have h : ∀ x : ℝ, (x - L/2) / R = x / R - (L/2) / R := fun x => sub_div _ _ _
  simp only [h]
  rw [intervalIntegral.integral_comp_div_sub f hR ((L/2) / R),
    show (L/2 - K * R) / R - (L/2) / R = -K by field_simp; ring,
    show (L/2) / R - (L/2) / R = (0:ℝ) by ring, smul_eq_mul]

theorem integrableOn_profile_pow (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    IntegrableOn (fun x => profile Cm Cp L R x ^ m) (Ioo (-L/2) (L/2)) := by
  have hcont := continuousOn_profile hR hL
  have hmeas : AEStronglyMeasurable (fun x => profile Cm Cp L R x ^ m)
      (volume.restrict (Ioo (-L/2) (L/2))) :=
    (hcont.pow m).aestronglyMeasurable measurableSet_Ioo
  refine Integrable.mono' (integrableOn_const (C := R ^ m) measure_Ioo_lt_top.ne) hmeas ?_
  refine ae_restrict_of_forall_mem measurableSet_Ioo (fun x hx => ?_)
  rw [Real.norm_eq_abs, abs_of_nonneg (pow_nonneg (profile_pos hR hL hx).le m)]
  exact pow_le_pow_left₀ (profile_pos hR hL hx).le (profile_le_R hR hL hx) m

/-- **The axial integral of `r_R^m`**: bulk plus the two rescaled cap integrals. -/
theorem integral_profile_pow (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    ∫ x in (-L/2)..(L/2), profile Cm Cp L R x ^ m
      = R ^ m * bulkLength Cm Cp L R
        + R ^ (m + 1) * ((∫ s in (-Cm.K)..(0:ℝ), Cm.θ s ^ m)
          + ∫ s in (-Cp.K)..(0:ℝ), Cp.θ s ^ m) := by
  have hmid := interface_lt (Cm := Cm) (Cp := Cp) hR hL
  have hl := left_lt_interface (Cm := Cm) (L := L) hR
  have hr := interface_lt_right (Cp := Cp) (L := L) hR
  have hint := integrableOn_profile_pow hR hL
  have i1 : IntervalIntegrable (fun x => profile Cm Cp L R x ^ m) volume
      (-L/2) (-L/2 + Cm.K * R) := by
    rw [intervalIntegrable_iff_integrableOn_Ioo_of_le hl.le]
    exact hint.mono_set (Ioo_subset_Ioo le_rfl (by linarith))
  have i2 : IntervalIntegrable (fun x => profile Cm Cp L R x ^ m) volume
      (-L/2 + Cm.K * R) (L/2 - Cp.K * R) := by
    rw [intervalIntegrable_iff_integrableOn_Ioo_of_le hmid.le]
    exact hint.mono_set (Ioo_subset_Ioo (by linarith) (by linarith))
  have i3 : IntervalIntegrable (fun x => profile Cm Cp L R x ^ m) volume
      (L/2 - Cp.K * R) (L/2) := by
    rw [intervalIntegrable_iff_integrableOn_Ioo_of_le hr.le]
    exact hint.mono_set (Ioo_subset_Ioo (by linarith) le_rfl)
  have hsplit : (∫ x in (-L/2)..(L/2), profile Cm Cp L R x ^ m)
      = (∫ x in (-L/2)..(-L/2 + Cm.K * R), profile Cm Cp L R x ^ m)
        + (∫ x in (-L/2 + Cm.K * R)..(L/2 - Cp.K * R), profile Cm Cp L R x ^ m)
        + ∫ x in (L/2 - Cp.K * R)..(L/2), profile Cm Cp L R x ^ m := by
    rw [intervalIntegral.integral_add_adjacent_intervals i1 i2,
      intervalIntegral.integral_add_adjacent_intervals (i1.trans i2) i3]
  have e1 : (∫ x in (-L/2)..(-L/2 + Cm.K * R), profile Cm Cp L R x ^ m)
      = R ^ (m + 1) * ∫ s in (-Cm.K)..(0:ℝ), Cm.θ s ^ m := by
    have hEq : EqOn (fun x => profile Cm Cp L R x ^ m)
        (fun x => R ^ m * Cm.θ ((-L/2 - x) / R) ^ m) (Ioo (-L/2) (-L/2 + Cm.K * R)) := by
      intro y hy
      simp only [profile_left hy.2, mul_pow]
    have hsub := integral_comp_left Cm.K R L hR.ne' (fun s => Cm.θ s ^ m)
    simp only at hsub
    rw [integral_congr_Ioo hl.le hEq, intervalIntegral.integral_const_mul, hsub, pow_succ]
    ring
  have e3 : (∫ x in (L/2 - Cp.K * R)..(L/2), profile Cm Cp L R x ^ m)
      = R ^ (m + 1) * ∫ s in (-Cp.K)..(0:ℝ), Cp.θ s ^ m := by
    have hEq : EqOn (fun x => profile Cm Cp L R x ^ m)
        (fun x => R ^ m * Cp.θ ((x - L/2) / R) ^ m) (Ioo (L/2 - Cp.K * R) (L/2)) := by
      intro y hy
      have hb : -L/2 + Cm.K * R ≤ y := le_of_lt (lt_trans hmid hy.1)
      simp only [profile_right hb hy.1, mul_pow]
    have hsub := integral_comp_right Cp.K R L hR.ne' (fun s => Cp.θ s ^ m)
    simp only at hsub
    rw [integral_congr_Ioo hr.le hEq, intervalIntegral.integral_const_mul, hsub, pow_succ]
    ring
  have e2 : (∫ x in (-L/2 + Cm.K * R)..(L/2 - Cp.K * R), profile Cm Cp L R x ^ m)
      = R ^ m * bulkLength Cm Cp L R := by
    have hEq : EqOn (fun x => profile Cm Cp L R x ^ m) (fun _ => R ^ m)
        (Ioo (-L/2 + Cm.K * R) (L/2 - Cp.K * R)) := by
      intro y hy
      simp only [profile_bulk hy.1.le hy.2.le]
    rw [integral_congr_Ioo hmid.le hEq, intervalIntegral.integral_const, smul_eq_mul,
      bulkLength]
    ring
  rw [hsplit, e1, e2, e3]
  ring

/-- **The volume of the thin domain**:
`|Ω_R| = ω_m R^m ℓ_R + R^{m+1} (|C₋| + |C₊|)` with `ℓ_R = L - (K₋+K₊)R`. -/
theorem volume_thinDomain (hR : 0 < R) (hL : (Cm.K + Cp.K) * R < L) :
    volume (thinDomain Cm Cp L R)
      = ENNReal.ofReal (omega m * R ^ m * bulkLength Cm Cp L R
          + R ^ (m + 1) * (Cm.revolutionVolume + Cp.revolutionVolume)) := by
  have hL0 : 0 < L := span_pos (Cm := Cm) (Cp := Cp) hR hL
  have hBfin : volume (ball (0 : EuclideanSpace ℝ (Fin m)) 1) ≠ ∞ := measure_ball_lt_top.ne
  have hmeas : MeasurableSet (thinDomain Cm Cp L R) := measurableSet_thinDomain hR hL
  have hprod : volume (thinDomain Cm Cp L R)
      = ∫⁻ x, volume (Prod.mk x ⁻¹' thinDomain Cm Cp L R) := Measure.prod_apply hmeas
  have hslice : ∀ x : ℝ, volume (Prod.mk x ⁻¹' thinDomain Cm Cp L R)
      = (Ioo (-L/2) (L/2)).indicator
          (fun x => ENNReal.ofReal (profile Cm Cp L R x ^ m)
            * volume (ball (0 : EuclideanSpace ℝ (Fin m)) 1)) x := by
    intro x
    have hpre : Prod.mk x ⁻¹' thinDomain Cm Cp L R =
        if x ∈ Ioo (-L/2) (L/2) then ball (0 : EuclideanSpace ℝ (Fin m))
          (profile Cm Cp L R x) else ∅ := by
      ext z
      simp only [thinDomain, mem_preimage, mem_setOf_eq, mem_Ioo]
      split_ifs with hx
      · simp [hx.1, hx.2]
      · simp only [mem_empty_iff_false, iff_false]
        intro h
        exact hx ⟨h.1, h.2.1⟩
    rw [hpre]
    by_cases hx : x ∈ Ioo (-L/2) (L/2)
    · rw [if_pos hx, indicator_of_mem hx, volume_ball_eq_pow_mul m (profile_pos hR hL hx)]
    · rw [if_neg hx, indicator_of_notMem hx, measure_empty]
  have hnn : 0 ≤ᵐ[volume.restrict (Ioo (-L/2) (L/2))] fun x => profile Cm Cp L R x ^ m :=
    ae_restrict_of_forall_mem measurableSet_Ioo
      (fun x hx => pow_nonneg (profile_pos hR hL hx).le m)
  have hint : ∫ x in Ioo (-L/2) (L/2), profile Cm Cp L R x ^ m
      = ∫ x in (-L/2)..(L/2), profile Cm Cp L R x ^ m := by
    rw [intervalIntegral.integral_of_le (by linarith), integral_Ioc_eq_integral_Ioo]
  have hnonneg : 0 ≤ ∫ x in Ioo (-L/2) (L/2), profile Cm Cp L R x ^ m :=
    setIntegral_nonneg measurableSet_Ioo (fun x hx => pow_nonneg (profile_pos hR hL hx).le m)
  have hom : volume (ball (0 : EuclideanSpace ℝ (Fin m)) 1) = ENNReal.ofReal (omega m) := by
    rw [omega, ENNReal.ofReal_toReal hBfin]
  rw [hprod, lintegral_congr hslice, lintegral_indicator measurableSet_Ioo,
    lintegral_mul_const' _ _ hBfin,
    ← ofReal_integral_eq_lintegral_ofReal (integrableOn_profile_pow hR hL).integrable hnn,
    hom, ← ENNReal.ofReal_mul hnonneg, hint, integral_profile_pow hR hL]
  congr 1
  simp only [Cap.revolutionVolume]
  ring

/-! ## Hemispherical caps: the Euclidean capsule -/

theorem profile_hemisphere_bulk (_hR : 0 < R) (_hL : 2 * R < L) {x : ℝ}
    (h1 : -(L/2 - R) ≤ x) (h2 : x ≤ L/2 - R) :
    profile (hemisphere m) (hemisphere m) L R x = R := by
  refine profile_bulk ?_ ?_
  · show -L/2 + (1:ℝ) * R ≤ x
    rw [one_mul]; linarith
  · show x ≤ L/2 - (1:ℝ) * R
    rw [one_mul]; linarith

theorem profile_hemisphere_left (hR : 0 < R) (_hL : 2 * R < L) {x : ℝ}
    (_h1 : -L/2 < x) (h2 : x < -(L/2 - R)) :
    profile (hemisphere m) (hemisphere m) L R x
      = Real.sqrt (R ^ 2 - (x + (L/2 - R)) ^ 2) := by
  have hbr : x < -L/2 + (hemisphere m).K * R := by
    show x < -L/2 + (1:ℝ) * R
    rw [one_mul]; linarith
  rw [profile_left hbr]
  show R * Cap.semi 1 ((-L/2 - x) / R) = _
  rw [Cap.semi, show R * Real.sqrt (1 - ((-L/2 - x) / R + 1) ^ 2)
      = Real.sqrt (R ^ 2 * (1 - ((-L/2 - x) / R + 1) ^ 2)) by
    rw [Real.sqrt_mul (sq_nonneg R), Real.sqrt_sq hR.le]]
  congr 1
  field_simp
  ring

theorem profile_hemisphere_right (hR : 0 < R) (hL : 2 * R < L) {x : ℝ}
    (h1 : L/2 - R < x) (_h2 : x < L/2) :
    profile (hemisphere m) (hemisphere m) L R x
      = Real.sqrt (R ^ 2 - (x - (L/2 - R)) ^ 2) := by
  have hbl : -L/2 + (hemisphere m).K * R ≤ x := by
    show -L/2 + (1:ℝ) * R ≤ x
    rw [one_mul]; linarith
  have hbr : L/2 - (hemisphere m).K * R < x := by
    show L/2 - (1:ℝ) * R < x
    rw [one_mul]; linarith
  rw [profile_right hbl hbr]
  show R * Cap.semi 1 ((x - L/2) / R) = _
  rw [Cap.semi, show R * Real.sqrt (1 - ((x - L/2) / R + 1) ^ 2)
      = Real.sqrt (R ^ 2 * (1 - ((x - L/2) / R + 1) ^ 2)) by
    rw [Real.sqrt_mul (sq_nonneg R), Real.sqrt_sq hR.le]]
  congr 1
  field_simp
  ring

/-- **The hemispherical thin domain is the Euclidean capsule.**  For two unit
hemispherical caps, `Ω_R` is exactly the set of points at distance `< R` from
the axial segment `[-(L/2-R), L/2-R] × {0}` (manuscript `eq:capsule-domain`). -/
theorem mem_thinDomain_hemisphere_iff (hR : 0 < R) (hL : 2 * R < L) {p : CapSpace m} :
    p ∈ thinDomain (hemisphere m) (hemisphere m) L R ↔
      ∃ t ∈ Icc (-(L/2 - R)) (L/2 - R), (p.1 - t) ^ 2 + ‖p.2‖ ^ 2 < R ^ 2 := by
  have ha : 0 < L/2 - R := by linarith
  constructor
  · rintro ⟨h1, h2, h3⟩
    rcases lt_or_ge p.1 (-(L/2 - R)) with hA | hA
    · refine ⟨-(L/2 - R), ⟨le_rfl, by linarith⟩, ?_⟩
      rw [profile_hemisphere_left hR hL h1 hA] at h3
      have := (Real.lt_sqrt (norm_nonneg p.2)).1 h3
      have hx : p.1 - -(L/2 - R) = p.1 + (L/2 - R) := by ring
      rw [hx]
      linarith
    · rcases le_or_gt p.1 (L/2 - R) with hB | hB
      · refine ⟨p.1, ⟨hA, hB⟩, ?_⟩
        rw [profile_hemisphere_bulk hR hL hA hB] at h3
        have h0 : ‖p.2‖ ^ 2 < R ^ 2 := by nlinarith [norm_nonneg p.2]
        simpa using h0
      · refine ⟨L/2 - R, ⟨by linarith, le_rfl⟩, ?_⟩
        rw [profile_hemisphere_right hR hL hB h2] at h3
        have := (Real.lt_sqrt (norm_nonneg p.2)).1 h3
        linarith
  · rintro ⟨t, ⟨ht1, ht2⟩, hlt⟩
    have hsq : (p.1 - t) ^ 2 < R ^ 2 := by nlinarith [sq_nonneg ‖p.2‖]
    have habs : |p.1 - t| < R := by
      rw [abs_lt]
      constructor <;> nlinarith
    rw [abs_lt] at habs
    refine ⟨by linarith [habs.1], by linarith [habs.2], ?_⟩
    rcases lt_or_ge p.1 (-(L/2 - R)) with hA | hA
    · rw [profile_hemisphere_left hR hL (by linarith [habs.1]) hA]
      rw [Real.lt_sqrt (norm_nonneg p.2)]
      nlinarith
    · rcases le_or_gt p.1 (L/2 - R) with hB | hB
      · rw [profile_hemisphere_bulk hR hL hA hB]
        nlinarith [norm_nonneg p.2, sq_nonneg (p.1 - t)]
      · rw [profile_hemisphere_right hR hL hB (by linarith [habs.2])]
        rw [Real.lt_sqrt (norm_nonneg p.2)]
        nlinarith

end

end Domain
end RobinCaps

